(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const images={quality:'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1400&q=84',long:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=84',strength:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1400&q=84',recovery:'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1400&q=84',easy:'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1400&q=84'};
function tone(el){if(el.classList.contains('smart-quality'))return'quality';if(el.classList.contains('smart-long'))return'long';if(el.classList.contains('smart-strength'))return'strength';if(el.classList.contains('smart-recovery'))return'recovery';return'easy'}
function enhanceToday(){const root=q('#today');if(!root?.classList.contains('active'))return;const hero=root.querySelector('.smart-today');if(!hero||hero.dataset.v19)return;hero.dataset.v19='1';const type=tone(hero),title=hero.querySelector('.today-training')?.textContent?.trim()||'',date=hero.querySelector('.today-date')?.textContent?.trim()||'',eyebrow=hero.querySelector('.today-eyebrow')?.textContent?.trim()||'';hero.classList.add('editorial-hero');hero.style.setProperty('--editorial-photo',`url("${images[type]}")`);const cover=document.createElement('div');cover.className='editorial-cover';cover.innerHTML=`<div class="editorial-cover-shade"></div><div class="editorial-cover-copy"><small>${esc(eyebrow.replace('AUJOURD’HHUI','AUJOURD’HUI'))}</small><h1>${esc(title)}</h1><p>${esc(date)}</p></div>`;hero.prepend(cover);const top=hero.querySelector('.today-top');if(top)top.classList.add('editorial-hidden');const oldEyebrow=hero.querySelector('.today-eyebrow');const oldTitle=hero.querySelector('.today-training');const oldDate=hero.querySelector('.today-date');[oldEyebrow,oldTitle,oldDate].forEach(x=>x?.classList.add('editorial-hidden'));const cta=hero.querySelector('.today-cta');if(cta){cta.classList.add('editorial-cta');cta.innerHTML='<span>Programme de la séance</span><b>→</b>'}const metrics=hero.querySelector('.today-metrics');if(metrics)metrics.classList.add('editorial-strip');
const brief=root.querySelector('.today-brief');if(brief&&!brief.dataset.v19){brief.dataset.v19='1';brief.classList.add('editorial-brief');const intro=document.createElement('div');intro.className='editorial-section-title';intro.innerHTML='<small>AVANT / APRÈS</small><h2>Les repères du jour</h2>';brief.before(intro)}
const report=root.querySelector('.today-report');if(report&&!report.dataset.v19copy){report.dataset.v19copy='1';const h=report.querySelector('h3');if(h)h.textContent='Après la séance'}
}
function routeSvg(pct,phase){const clamped=Math.max(0,Math.min(100,pct));const x=18+clamped*2.64;const milestones=[{x:18,l:'Départ'},{x:86,l:'Base'},{x:154,l:'Construction'},{x:222,l:'Spécifique'},{x:282,l:'Roma'}];return `<div class="rome-route" aria-label="Progression vers Rome"><svg viewBox="0 0 300 112" role="img"><defs><linearGradient id="routeGlow" x1="0" x2="1"><stop offset="0" stop-color="#7b1e2b"/><stop offset="1" stop-color="#d46a45"/></linearGradient></defs><path class="route-base" d="M18 74 C58 30,98 95,139 56 S220 42,282 62"/><path class="route-done" pathLength="100" stroke-dasharray="${clamped} ${100-clamped}" d="M18 74 C58 30,98 95,139 56 S220 42,282 62"/>${milestones.map(m=>`<circle cx="${m.x}" cy="${m.x===18?74:m.x===86?58:m.x===154?60:m.x===222?48:62}" r="4"/><text x="${m.x}" y="104" text-anchor="middle">${m.l}</text>`).join('')}<g class="route-you"><circle cx="${Math.min(282,Math.max(18,x))}" cy="55" r="9"/><circle cx="${Math.min(282,Math.max(18,x))}" cy="55" r="3"/></g></svg><div class="route-caption"><span>Position actuelle</span><b>${esc(phase||'Préparation marathon')}</b></div></div>`}
function enhanceProgress(){const root=q('#progress');if(!root?.classList.contains('active'))return;const card=root.querySelector('.journey-card');if(!card||card.dataset.v19)return;card.dataset.v19='1';const progressText=card.querySelector('.journey-progress-copy b')?.textContent||'';const m=progressText.match(/([\d,.]+)\s*%/);const pct=m?parseFloat(m[1].replace(',','.')):0;const next=card.querySelector('.journey-next b')?.textContent||'';let phase='Préparation marathon';try{const d=(window.APP_DATA?.weeks||[]).flatMap(w=>w.days.map(x=>({...x,phase:w.phase}))).find(x=>x.date>=new Date().toLocaleDateString('sv-SE'));if(d?.phase)phase=d.phase}catch{}const route=document.createElement('div');route.className='journey-route-wrap';route.innerHTML=`<div class="editorial-section-title"><small>LE PARCOURS</small><h2>De maintenant jusqu’à Rome</h2></div>${routeSvg(pct,phase)}`;const lead=card.querySelector('.journey-lead');lead?.insertAdjacentElement('afterend',route);if(next){const nextBox=card.querySelector('.journey-next');nextBox?.classList.add('editorial-next')}}
function enhanceWeek(){const root=q('#week');if(!root?.classList.contains('active'))return;const card=root.querySelector('.card');if(!card||card.dataset.v19)return;card.dataset.v19='1';card.classList.add('editorial-week');const h=card.querySelector('h2');if(h){const mast=document.createElement('div');mast.className='editorial-section-title';mast.innerHTML='<small>PROGRAMME</small><h2>Ta semaine</h2>';h.replaceWith(mast)}}
function run(){enhanceToday();enhanceProgress();enhanceWeek();document.body.classList.add('v19')}
new MutationObserver(()=>requestAnimationFrame(run)).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest?.('nav button'))setTimeout(run,80)},true);setTimeout(run,500);window.R42_V19={run};
})();