window.R42_ENGINE=(()=>{
const pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,monday=d=>{const x=new Date(d);x.setHours(12,0,0,0);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x},add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const phase=(i,n)=>{const r=i/Math.max(1,n-1);return r<.18?'Base':r<.50?'Construction':r<.82?'Spécifique marathon':'Affûtage'};
const level=p=>{const km=+p.weeklyKm||0,long=+p.longestRunKm||0;if(km>=55&&long>=24)return'advanced';if(km>=35&&long>=16)return'intermediate';return'beginner'};
const targetMinutes=p=>{const s=String(p.targetTime||'').trim().toLowerCase().replace(/\s/g,'');if(!s)return null;let m=s.match(/^(\d{1,2})h(?:(\d{1,2}))?$/);if(m)return+m[1]*60+(+(m[2]||0));m=s.match(/^(\d{1,2}):(\d{2})$/);if(m)return+m[1]*60+(+m[2]);const x=Number(s.replace(',','.'));return Number.isFinite(x)&&x>=2.3&&x<=7?Math.round(x*60):null};
const profile=p=>{const l=level(p),tm=targetMinutes(p),finish=p.goalType==='finish'||!tm;let band=finish?'finish':tm<=180?'elite':tm<=240?'performance':tm<=300?'recreational':'finish';return{l,tm,band,finish}};
const strategy=p=>{const x=profile(p);return x.finish?{type:'runwalk',label:'course/marche',race:'stratégie course/marche testée à l’entraînement'}:{type:'continuous',label:'course continue',race:`course continue · objectif ${Math.floor(x.tm/60)} h ${String(x.tm%60).padStart(2,'0')} · allure cible validée à l’entraînement`}};
function longMin(p,w,n){const x=profile(p),start=x.l==='advanced'?100:x.l==='intermediate'?80:55,peak=x.band==='elite'?180:x.band==='performance'?185:x.band==='recreational'?180:165;if(w>=n-3)return[120,80,35][Math.min(2,w-(n-3))];let v=start+(peak-start)*Math.min(1,w/Math.max(1,n-5));if((w+1)%4===0)v*=.75;return Math.round(v/5)*5}
function quality(p,ph,w){const x=profile(p),st=strategy(p),easy=st.type==='runwalk'?'course/marche très facile':'footing très facile';if(ph==='Affûtage')return x.finish?`30–40 min de ${easy} + 4 × 20 s de course relâchée, récupération complète très facile`:`15 min de footing facile + 3 × 5 min à allure marathon, récup 2 min en footing très lent + 10 min de retour au calme`;if(x.finish)return ph==='Base'?`Fartlek doux : 15 min de ${easy} + 6 × 1 min de course soutenue / 2 min très faciles + retour au calme`:ph==='Construction'?`Côtes : 15 min de ${easy} + 6 × 45 s de course en côte RPE 6, récupération en marchant ou trottinant en descente + retour au calme`:`Allure marathon / course-marche : 15 min de ${easy} + 3 × 10 min à effort marathon, récup 3 min très faciles + retour au calme`;if(ph==='Base')return'15 min de footing facile + 8 × 45 s de course en côte RPE 6, récupération en descente + 10 min de footing très facile';if(ph==='Construction'){const reps=x.band==='elite'?6:x.band==='performance'?5:4;return`Fractionné : 15–20 min de footing facile + ${reps} × 1 km à allure 10 km (RPE 7–8), récup 2 min en trot très lent + 10–15 min de footing très facile`;}return x.band==='elite'?'Spécifique marathon : 20 min de footing facile + 3 × 5 km à allure marathon, récup 1 km en footing facile + retour au calme':'Spécifique marathon : 15 min de footing facile + 3 × 12–15 min à allure marathon, récup 3 min en footing très lent + retour au calme'}
function strength(ph){return ph==='Affûtage'?'Renforcement entretien 15–20 min : gainage, mollets, fessiers, mobilité · aucune fatigue résiduelle':'Renforcement 25–35 min : squat/fente, charnière de hanche, mollets, fessiers, gainage · 2–3 séries, technique propre, sans aller à l’échec'}
function makeWeek(p,w,n,startDate,raceISO){const ph=phase(w,n),st=strategy(p),L=longMin(p,w,n),avail=[...new Set((p.days||[2,4,6]).map(Number))].sort(),longDay=Number(p.longDay??6);if(!avail.includes(longDay))avail.push(longDay);avail.sort();const x=profile(p),qualityDay=avail.find(d=>d!==longDay),strengthCandidates=[1,3,5].filter(d=>d!==longDay&&!avail.includes(d));const strengthDays=strengthCandidates.slice(0,x.l==='advanced'?2:1);const days=[];for(let i=0;i<7;i++){const d=add(startDate,i),date=iso(d);let training='Repos / mobilité douce 10–15 min',nutritionNote='Hydratation normale, protéines à chaque repas, glucides adaptés à la charge.';if(date===raceISO){training=`MARATHON DE ROME · 42,195 km · ${st.race} · départ contrôlé · ravitaillement uniquement selon le protocole validé`;nutritionNote='JOUR J : petit-déjeuner et ravitaillement déjà testés. Ne rien expérimenter.'}else if(i===longDay){const mode=st.type==='runwalk'?'course/marche selon la stratégie validée dès le départ':'course continue en endurance';training=`Sortie longue ${Math.floor(L/60)?Math.floor(L/60)+' h ':''}${L%60?L%60+' min':''} · ${mode} · effort facile RPE 3–4${ph==='Spécifique marathon'&&!x.finish?' · finir 20–40 min à allure marathon si récupération normale':''} · plafond volontaire ≈ ${L} min`;nutritionNote='Pendant >90 min : entraîner le ravitaillement et l’hydratation.'}else if(i===qualityDay){training=quality(p,ph,w)}else if(avail.includes(i)){if(st.type==='runwalk')training=ph==='Affûtage'?'Course/marche très facile 25–45 min · alternance habituelle · RPE 2–3':avail.length>=5?'Course/marche facile 45–70 min · alternance habituelle · RPE 3–4':'Course/marche facile 35–55 min · alternance habituelle · RPE 3–4';else training=ph==='Affûtage'?'Footing très facile 25–45 min · course à pied · RPE 2–3':avail.length>=5?'Footing facile 45–70 min · course à pied · RPE 3–4':'Footing facile 35–55 min · course à pied · RPE 3–4'}else if(strengthDays.includes(i)){training=strength(ph)}days.push({date,training,menu:'GEN',nutritionNote})}return{week:w+1,phase:ph,days}}
function generate(p){const raceISO=p.raceDate||window.R42_RACE?.date||'2027-03-14',race=new Date(raceISO+'T12:00:00'),start=monday(new Date()),weeks=Math.max(1,Math.floor(Math.max(0,race-start)/(7*86400000))+1),arr=[];for(let w=0;w<weeks;w++)arr.push(makeWeek(p,w,weeks,add(start,w*7),raceISO));return arr}
return{generate,level,strategy,targetMinutes,profile};
})();