(()=>{
const C=window.ROME42_FIREBASE_CONFIG;
if(!C||!window.firebase)return;
const app=firebase.apps.length?firebase.app():firebase.initializeApp(C);
const auth=firebase.auth();
const db=firebase.firestore();
const KEYS=['rome42-v1','rome42-settings-v1','rome42-profile-v2','rome42-nutrition-profile-v1','rome42-household-v2'];
let user=null,hydrating=false,syncTimer=null;
const parse=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
const payload=()=>({profile:parse('rome42-profile-v2'),state:parse('rome42-v1'),settings:parse('rome42-settings-v1'),nutritionProfile:parse('rome42-nutrition-profile-v1'),household:parse('rome42-household-v2'),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});
const doc=()=>user?db.collection('users').doc(user.uid):null;
async function push(){if(!user||hydrating)return;try{await doc().set(payload(),{merge:true})}catch(e){console.warn('Rome42 sync:',e.code||e.message)}}
function schedule(){clearTimeout(syncTimer);syncTimer=setTimeout(push,500)}
const nativeSet=Storage.prototype.setItem;
Storage.prototype.setItem=function(k,v){nativeSet.call(this,k,v);if(this===localStorage&&KEYS.includes(k))schedule()};
function hasLocalProfile(){return !!parse('rome42-profile-v2')}
async function hydrate(){if(!user)return;hydrating=true;try{const snap=await doc().get();if(snap.exists){const d=snap.data();const map={'rome42-profile-v2':d.profile,'rome42-v1':d.state,'rome42-settings-v1':d.settings,'rome42-nutrition-profile-v1':d.nutritionProfile,'rome42-household-v2':d.household};const cloudHasProfile=!!d.profile;if(cloudHasProfile){Object.entries(map).forEach(([k,v])=>{if(v!==undefined&&v!==null)nativeSet.call(localStorage,k,JSON.stringify(v))})}else if(hasLocalProfile())await doc().set(payload(),{merge:true})}else{await doc().set({...payload(),email:user.email,createdAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}}finally{hydrating=false}}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function authUI(){let el=document.getElementById('r42-auth');if(el)return el;el=document.createElement('div');el.id='r42-auth';el.innerHTML=`<div class="auth-shell auth-welcome" id="auth-welcome"><div class="auth-brand"><div class="auth-icon">R42</div><div><p class="auth-kicker">ROAD TO ROME · MMXXVII</p><div class="auth-logo">ROME<span>42</span></div></div></div><div class="auth-hero-copy"><small>TA PRÉPARATION MARATHON, AU MÊME ENDROIT</small><h1>Ton chemin vers Rome commence ici.</h1><p>Un plan adapté à ton profil, tes séances du jour, ta nutrition, ton suivi et ton foyer — dans une seule application.</p></div><div class="auth-benefits"><div><b>01</b><span><strong>Un plan qui te ressemble</strong><small>Objectif, niveau, disponibilité et progression.</small></span></div><div><b>02</b><span><strong>Chaque jour, l’essentiel</strong><small>Séance, récupération, nutrition et repères utiles.</small></span></div><div><b>03</b><span><strong>0 €</strong><small>Pas d’abonnement pour utiliser Rome42.</small></span></div></div><button class="btn auth-primary" id="auth-start">Créer mon compte</button><button class="auth-switch" id="auth-login-existing">J’ai déjà un compte</button><p class="auth-trust">Tes données restent associées à ton compte Rome42 pour retrouver ton suivi sur un autre appareil.</p></div><div class="auth-shell auth-form-shell" id="auth-panel" hidden><button class="auth-back" id="auth-back" aria-label="Retour">←</button><div class="auth-logo small-logo">ROME<span>42</span></div><p class="auth-kicker">ROAD TO ROME · MMXXVII</p><h2 id="auth-title">Créer mon compte</h2><p class="auth-copy" id="auth-copy">Quelques secondes suffisent. Tu configureras ensuite ton profil et ton objectif marathon.</p><form id="auth-form"><label>Adresse e-mail</label><input id="auth-email" type="email" autocomplete="email" required><label>Mot de passe</label><input id="auth-password" type="password" autocomplete="new-password" minlength="6" required><button class="btn" type="submit">Créer mon compte</button></form><button class="auth-switch" id="auth-switch">J’ai déjà un compte</button><p id="auth-error" class="auth-error"></p></div>`;document.body.appendChild(el);
let signup=true;const welcome=el.querySelector('#auth-welcome'),panel=el.querySelector('#auth-panel'),title=el.querySelector('#auth-title'),copy=el.querySelector('#auth-copy'),form=el.querySelector('#auth-form'),sw=el.querySelector('#auth-switch'),err=el.querySelector('#auth-error'),pass=el.querySelector('#auth-password');
function setMode(isSignup){signup=isSignup;title.textContent=signup?'Créer mon compte':'Se connecter';copy.textContent=signup?'Quelques secondes suffisent. Tu configureras ensuite ton profil et ton objectif marathon.':'Retrouve ton plan, ton foyer et ta progression Rome42.';form.querySelector('button').textContent=signup?'Créer mon compte':'Se connecter';sw.textContent=signup?'J’ai déjà un compte':'Créer un compte Rome42';pass.autocomplete=signup?'new-password':'current-password';err.textContent=''}
function showForm(isSignup){setMode(isSignup);welcome.hidden=true;panel.hidden=false;setTimeout(()=>el.querySelector('#auth-email')?.focus(),150)}
el.querySelector('#auth-start').onclick=()=>showForm(true);el.querySelector('#auth-login-existing').onclick=()=>showForm(false);el.querySelector('#auth-back').onclick=()=>{panel.hidden=true;welcome.hidden=false;err.textContent=''};sw.onclick=()=>setMode(!signup);
form.onsubmit=async e=>{e.preventDefault();err.textContent='';const email=el.querySelector('#auth-email').value.trim(),password=pass.value;try{if(signup)await auth.createUserWithEmailAndPassword(email,password);else await auth.signInWithEmailAndPassword(email,password)}catch(x){const msgs={'auth/email-already-in-use':'Cette adresse possède déjà un compte.','auth/invalid-credential':'E-mail ou mot de passe incorrect.','auth/weak-password':'Choisis un mot de passe d’au moins 6 caractères.','auth/invalid-email':'Adresse e-mail invalide.'};err.textContent=msgs[x.code]||'Connexion impossible. Réessaie.'}};return el}
function injectAccount(){const settings=document.querySelector('#settings');if(!settings||!user)return;if(settings.querySelector('#r42-account'))return;const card=document.createElement('div');card.className='card';card.id='r42-account';card.innerHTML=`<span class="tag">COMPTE ROME42</span><h2>Synchronisation active</h2><p class="muted">${esc(user.email)}</p><p class="muted small">Ton profil et tes données personnelles sont synchronisés avec ton compte.</p><button class="btn secondary" id="r42-sync-now">Synchroniser maintenant</button><button class="btn secondary" id="r42-logout">Se déconnecter</button>`;settings.prepend(card);card.querySelector('#r42-sync-now').onclick=async()=>{await push();alert('Synchronisation terminée.')};card.querySelector('#r42-logout').onclick=()=>auth.signOut()}
new MutationObserver(injectAccount).observe(document.documentElement,{subtree:true,childList:true});
auth.onAuthStateChanged(async u=>{user=u;if(!u){authUI();return}const overlay=document.getElementById('r42-auth');if(overlay)overlay.remove();await hydrate();injectAccount();if(!sessionStorage.getItem('r42-cloud-ready')){sessionStorage.setItem('r42-cloud-ready','1');location.reload()}else{push()}});
window.R42_CLOUD={auth,db,sync:push,currentUser:()=>user};
})();