(()=>{
function ready(){return window.R42_CLOUD&&R42_CLOUD.currentUser()}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const db=()=>R42_CLOUD.db, me=()=>R42_CLOUD.currentUser();
const localProfiles=()=>{try{return JSON.parse(localStorage.getItem('rome42-household-v2')||'[]')}catch{return[]}};
async function myUser(){return (await db().collection('users').doc(me().uid).get()).data()||{}}
function profileKey(x){return x.id||[String(x.name||'').trim().toLowerCase(),String(x.age||'')].join('|')}
function mergeProfiles(cloud,local){const out=[],seen=new Map();[...(cloud||[]),...(local||[])].forEach(x=>{if(!x||!x.name)return;const k=profileKey(x);if(seen.has(k)){Object.assign(seen.get(k),x)}else{const y={...x};seen.set(k,y);out.push(y)}});return out}
async function syncProfiles(householdId){const ref=db().collection('households').doc(householdId),snap=await ref.get();if(!snap.exists)return[];const cloud=snap.data().profiles||[],merged=mergeProfiles(cloud,localProfiles());if(JSON.stringify(merged)!==JSON.stringify(cloud))await ref.set({profiles:merged,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});localStorage.setItem('rome42-household-v2',JSON.stringify(merged));return merged}
async function ensureHousehold(){let u=await myUser();if(u.householdId){await syncProfiles(u.householdId);return u.householdId}const ref=db().collection('households').doc(),p=u.profile||{},profiles=mergeProfiles([],localProfiles());await ref.set({ownerId:me().uid,members:{[me().uid]:{name:p.name||me().email,email:me().email,role:'owner'}},profiles,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await db().collection('users').doc(me().uid).set({householdId:ref.id},{merge:true});return ref.id}
async function createInvite(){const householdId=await ensureHousehold(),inviteCode=code();await db().collection('householdInvites').doc(inviteCode).set({householdId,createdBy:me().uid,createdByEmail:me().email,status:'open',createdAt:firebase.firestore.FieldValue.serverTimestamp()});return inviteCode}
async function acceptInvite(inviteCode){inviteCode=inviteCode.trim().toUpperCase();if(!inviteCode)throw Error('Saisis le code reçu.');const ref=db().collection('householdInvites').doc(inviteCode),snap=await ref.get();if(!snap.exists||snap.data().status!=='open')throw Error('Invitation introuvable ou déjà utilisée.');const inv=snap.data(),u=await myUser(),p=u.profile||{},hRef=db().collection('households').doc(inv.householdId),hSnap=await hRef.get();if(!hSnap.exists)throw Error('Le foyer associé à cette invitation n’existe plus.');const h=hSnap.data(),members={...(h.members||{})};members[me().uid]={name:p.name||me().email,email:me().email,role:'member'};const profiles=mergeProfiles(h.profiles||[],localProfiles());await hRef.set({members,profiles,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await db().collection('users').doc(me().uid).set({householdId:inv.householdId},{merge:true});localStorage.setItem('rome42-household-v2',JSON.stringify(profiles));await ref.set({status:'accepted',acceptedBy:me().uid,acceptedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return inv.householdId}
function joinedPopup(){let x=document.getElementById('r42-household-confirm');if(x)x.remove();x=document.createElement('div');x.id='r42-household-confirm';x.style.cssText='position:fixed;inset:0;z-index:99999;background:rgba(20,10,10,.58);display:grid;place-items:center;padding:24px';x.innerHTML=`<div class="card" style="max-width:390px;width:100%;text-align:center"><span class="tag">FOYER ROME42</span><h2>Foyer rejoint ✓</h2><p class="muted">Ton compte est maintenant rattaché au foyer partagé.</p><button class="btn" id="r42-house-ok">Continuer</button></div>`;document.body.appendChild(x);x.querySelector('#r42-house-ok').onclick=()=>location.reload()}
async function render(){if(!ready())return;const settings=document.querySelector('#settings');if(!settings)return;const old=settings.querySelector('#r42-household-cloud');if(old)old.remove();let u=await myUser(),members=[],profiles=[];if(u.householdId){profiles=await syncProfiles(u.householdId);const h=await db().collection('households').doc(u.householdId).get(),d=h.data()||{};members=Object.values(d.members||{})}const card=document.createElement('div');card.className='card';card.id='r42-household-cloud';card.innerHTML=`<span class="tag">FOYER ROME42</span><h2>Mon foyer</h2><p class="muted small">Comptes Rome42 liés et profils du foyer sont regroupés ici.</p><h3>Comptes Rome42</h3>${members.length?members.map(x=>`<div class="memberrow"><div><b>${esc(x.name)}</b><small>${esc(x.email)}${x.role==='owner'?' · administrateur':''}</small></div></div>`).join(''):'<p class="muted small">Aucun compte lié.</p>'}<h3>Autres membres du foyer</h3>${profiles.length?profiles.map(x=>`<div class="memberrow"><div><b>${esc(x.name)}</b><small>Profil foyer${x.age?' · '+esc(x.age)+' ans':''}</small></div></div>`).join(''):'<p class="muted small">Aucun profil supplémentaire.</p>'}<button class="btn secondary" id="r42-create-invite">Inviter un compte Rome42</button><details><summary>J’ai reçu un code d’invitation</summary><label>Code foyer</label><input id="r42-invite-code" maxlength="6" autocapitalize="characters" placeholder="ABC123"><button class="btn" id="r42-accept-invite">Rejoindre le foyer</button></details><p id="r42-house-msg" class="muted small"></p>`;settings.appendChild(card);const msg=card.querySelector('#r42-house-msg');card.querySelector('#r42-create-invite').onclick=async()=>{try{msg.textContent='Création de l’invitation…';const c=await createInvite();msg.innerHTML=`Code à transmettre : <b style="font-size:1.3em;letter-spacing:.12em">${c}</b>`}catch(e){msg.textContent='Impossible de créer l’invitation : '+e.message}};card.querySelector('#r42-accept-invite').onclick=async()=>{try{msg.textContent='Rattachement en cours…';await acceptInvite(card.querySelector('#r42-invite-code').value);joinedPopup()}catch(e){msg.textContent=e.message}}}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>render().catch(console.warn),250)}).observe(document.documentElement,{subtree:true,childList:true});setTimeout(()=>render().catch(console.warn),1200);
window.R42_HOUSEHOLD_CLOUD={createInvite,acceptInvite,ensureHousehold,syncProfiles};
})();