(()=>{
function ready(){return window.R42_CLOUD&&R42_CLOUD.currentUser()}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const db=()=>R42_CLOUD.db, me=()=>R42_CLOUD.currentUser();
async function myUser(){return (await db().collection('users').doc(me().uid).get()).data()||{}}
async function ensureHousehold(){let u=await myUser();if(u.householdId)return u.householdId;const ref=db().collection('households').doc();const profile=u.profile||{};await ref.set({ownerId:me().uid,members:{[me().uid]:{name:profile.name||me().email,email:me().email,role:'owner'}},createdAt:firebase.firestore.FieldValue.serverTimestamp()});await db().collection('users').doc(me().uid).set({householdId:ref.id},{merge:true});return ref.id}
async function createInvite(){const householdId=await ensureHousehold(),inviteCode=code();await db().collection('householdInvites').doc(inviteCode).set({householdId,createdBy:me().uid,createdByEmail:me().email,status:'open',createdAt:firebase.firestore.FieldValue.serverTimestamp()});return inviteCode}
async function acceptInvite(inviteCode){inviteCode=inviteCode.trim().toUpperCase();if(!inviteCode)throw Error('Saisis le code reçu.');const ref=db().collection('householdInvites').doc(inviteCode),snap=await ref.get();if(!snap.exists||snap.data().status!=='open')throw Error('Invitation introuvable ou déjà utilisée.');const inv=snap.data(),u=await myUser(),p=u.profile||{};await db().collection('households').doc(inv.householdId).set({lastJoinCode:inviteCode,members:{[me().uid]:{name:p.name||me().email,email:me().email,role:'member'}}},{merge:true});await db().collection('users').doc(me().uid).set({householdId:inv.householdId},{merge:true});await ref.set({status:'accepted',acceptedBy:me().uid,acceptedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return inv.householdId}
async function render(){if(!ready())return;const settings=document.querySelector('#settings');if(!settings||settings.querySelector('#r42-household-cloud'))return;let u=await myUser(),members=[];if(u.householdId){const h=await db().collection('households').doc(u.householdId).get();members=Object.values(h.data()?.members||{})}const card=document.createElement('div');card.className='card';card.id='r42-household-cloud';card.innerHTML=`<span class="tag">FOYER ROME42</span><h2>Comptes liés</h2><p class="muted small">Chaque personne conserve son propre compte et son propre plan. Le foyer sert aux fonctions communes, notamment la nutrition.</p>${members.length?members.map(x=>`<div class="memberrow"><div><b>${esc(x.name)}</b><small>${esc(x.email)}${x.role==='owner'?' · administrateur':''}</small></div></div>`).join(''):'<p class="muted">Aucun autre compte lié.</p>'}<button class="btn secondary" id="r42-create-invite">Inviter un compte Rome42</button><details><summary>J’ai reçu un code d’invitation</summary><label>Code foyer</label><input id="r42-invite-code" maxlength="6" autocapitalize="characters" placeholder="ABC123"><button class="btn" id="r42-accept-invite">Rejoindre le foyer</button></details><p id="r42-house-msg" class="muted small"></p>`;settings.appendChild(card);const msg=card.querySelector('#r42-house-msg');card.querySelector('#r42-create-invite').onclick=async()=>{try{msg.textContent='Création de l’invitation…';const c=await createInvite();msg.innerHTML=`Code à transmettre : <b style="font-size:1.3em;letter-spacing:.12em">${c}</b><br>L’autre personne ouvre Réglages → Foyer Rome42 → « J’ai reçu un code d’invitation ».`}catch(e){msg.textContent='Impossible de créer l’invitation : '+e.message}};card.querySelector('#r42-accept-invite').onclick=async()=>{try{msg.textContent='Rattachement en cours…';await acceptInvite(card.querySelector('#r42-invite-code').value);msg.textContent='Compte rattaché au foyer ✓';setTimeout(()=>location.reload(),700)}catch(e){msg.textContent=e.message}}}
new MutationObserver(()=>render().catch(console.warn)).observe(document.documentElement,{subtree:true,childList:true});setTimeout(()=>render().catch(console.warn),1200);
window.R42_HOUSEHOLD_CLOUD={createInvite,acceptInvite};
})();