(()=>{
const STORE='rome42-meal-overrides-v1';
const N=()=>window.R42_NUTRITION;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const extras={
 H:{lunch:{name:'Bowl poulet, quinoa & légumes rôtis',ingredients:[['Poulet',240,'g','Protéines'],['Quinoa',240,'g','Féculents'],['Courgettes / poivrons',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Yaourt nature',1,'pot','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},dinner:{name:'Crevettes, riz & légumes sautés',ingredients:[['Crevettes',260,'g','Poisson'],['Riz',250,'g','Féculents'],['Légumes asiatiques',350,'g','Fruits & légumes'],['Sauce soja',1,'à prévoir','Épicerie'],['Huile d’olive',10,'g','Épicerie']]},snack:[['Skyr',250,'g','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},
 I:{lunch:{name:'Poulet citron, boulgour & ratatouille',ingredients:[['Poulet',250,'g','Protéines'],['Boulgour',260,'g','Féculents'],['Ratatouille',380,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Citron',1,'pièce','Fruits & légumes']]},dinner:{name:'Truite, patate douce & haricots verts',ingredients:[['Truite',230,'g','Poisson'],['Patate douce',380,'g','Féculents'],['Haricots verts',350,'g','Fruits & légumes'],['Huile d’olive',10,'g','Épicerie'],['Fromage blanc',200,'g','Produits frais']]},snack:[['Banane',1,'pièce','Fruits & légumes'],['Amandes',20,'g','Épicerie']]},
 J:{lunch:{name:'Boulettes de dinde, polenta & légumes',ingredients:[['Dinde',250,'g','Protéines'],['Polenta',270,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Sauce tomate',180,'g','Épicerie'],['Huile d’olive',10,'g','Épicerie']]},dinner:{name:'Frittata pommes de terre & épinards',ingredients:[['Œufs',4,'pièce','Produits frais'],['Pommes de terre',350,'g','Féculents'],['Épinards',300,'g','Fruits & légumes'],['Salade verte',150,'g','Fruits & légumes'],['Fromage blanc',200,'g','Produits frais']]},snack:[['Skyr',250,'g','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},
 K:{lunch:{name:'Saumon teriyaki, riz & brocoli',ingredients:[['Saumon',220,'g','Poisson'],['Riz',260,'g','Féculents'],['Brocoli',350,'g','Fruits & légumes'],['Sauce soja',1,'à prévoir','Épicerie'],['Miel',1,'à prévoir','Épicerie']]},dinner:{name:'Poulet paprika, semoule & légumes',ingredients:[['Poulet',250,'g','Protéines'],['Semoule',270,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Yaourt nature',1,'pot','Produits frais']]},snack:[['Banane',1,'pièce','Fruits & légumes'],['Noix',20,'g','Épicerie']]},
 L:{lunch:{name:'Pâtes au thon, tomate & courgette',ingredients:[['Thon',220,'g','Poisson'],['Pâtes',290,'g','Féculents'],['Sauce tomate',180,'g','Épicerie'],['Courgettes',320,'g','Fruits & légumes'],['Parmesan',20,'g','Produits frais']]},dinner:{name:'Dahl de lentilles, riz & légumes',ingredients:[['Lentilles corail',220,'g','Épicerie'],['Riz',230,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Lait de coco léger',100,'ml','Épicerie'],['Curry',1,'à prévoir','Épicerie']]},snack:[['Skyr',250,'g','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},
 M:{lunch:{name:'Poulet pesto, pâtes & tomates',ingredients:[['Poulet',240,'g','Protéines'],['Pâtes',280,'g','Féculents'],['Tomates',300,'g','Fruits & légumes'],['Pesto',30,'g','Épicerie'],['Parmesan',15,'g','Produits frais']]},dinner:{name:'Cabillaud provençal, pommes de terre & légumes',ingredients:[['Cabillaud',270,'g','Poisson'],['Pommes de terre',380,'g','Féculents'],['Tomates / courgettes',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie']]},snack:[['Banane',1,'pièce','Fruits & légumes'],['Fromage blanc',220,'g','Produits frais']]},
 N:{lunch:{name:'Burrito bowl bœuf, riz & haricots',ingredients:[['Bœuf haché 5 %',220,'g','Protéines'],['Riz',230,'g','Féculents'],['Haricots rouges',160,'g','Épicerie'],['Tomates / maïs / salade',320,'g','Fruits & légumes'],['Yaourt nature',1,'pot','Produits frais']]},dinner:{name:'Poulet rôti, patate douce & brocoli',ingredients:[['Poulet',250,'g','Protéines'],['Patate douce',380,'g','Féculents'],['Brocoli',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Skyr',200,'g','Produits frais']]},snack:[['Fruit',1,'pièce','Fruits & légumes'],['Amandes',20,'g','Épicerie']]}
};
const extraPhotos={
 H:{lunch:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80'},
 I:{lunch:'https://images.unsplash.com/photo-1539136788836-5699e78bfc75?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80'},
 J:{lunch:'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80'},
 K:{lunch:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80'},
 L:{lunch:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'},
 M:{lunch:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80'},
 N:{lunch:'https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80'}
};
function installExtras(){const n=N();if(!n)return;Object.assign(n.lib,extras);Object.assign(n.photos,extraPhotos)}
function read(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}}
function save(x){localStorage.setItem(STORE,JSON.stringify(x))}
function slotFor(day,part){const label=day.querySelector('.menu-day-head b')?.textContent?.trim()||'';return`${label}|${part}`}
function details(code,part){const x=N()?.lib?.[code]?.[part];return x?.ingredients?.slice(0,4).map(([n,q,u])=>`${n} ${typeof q==='number'?q+' '+u:''}`).join(' · ')||''}
function applyCard(card,code){const part=card.dataset.part,m=N()?.meal?.(code,part);if(!m)return;card.dataset.code=code;const img=card.querySelector('img');if(img){img.src=m.photo;img.alt=m.name}const body=card.querySelector('.meal-body');if(body){const bs=body.querySelectorAll('b');if(bs[0])bs[0].textContent=m.name;const ss=body.querySelectorAll('small');if(ss[1])ss[1].textContent=details(code,part)}}
function applyOverrides(){installExtras();const o=read();document.querySelectorAll('#nutrition .menu-day').forEach(day=>day.querySelectorAll('.recipe-open[data-part]').forEach(card=>{const code=o[slotFor(day,card.dataset.part)];if(code)applyCard(card,code)}))}
function suggestions(current,part){const visible=new Set([...document.querySelectorAll(`#nutrition .recipe-open[data-part="${part}"]`)].map(x=>x.dataset.code));const all=Object.keys(N()?.lib||{}).filter(c=>c!==current);const preferred=all.filter(c=>!visible.has(c));const pool=(preferred.length>=3?preferred:all).sort(()=>Math.random()-.5);return pool.slice(0,3)}
async function cloudSave(overrides){try{if(!window.R42_CLOUD?.currentUser?.())return;const u=R42_CLOUD.currentUser(),db=R42_CLOUD.db,s=await db.collection('users').doc(u.uid).get(),hid=s.data()?.householdId;if(hid)await db.collection('households').doc(hid).set({mealOverrides:overrides},{merge:true})}catch(e){console.warn('Rome42 meal override sync',e)}}
async function cloudLoad(){try{if(!window.R42_CLOUD?.currentUser?.())return;const u=R42_CLOUD.currentUser(),db=R42_CLOUD.db,s=await db.collection('users').doc(u.uid).get(),hid=s.data()?.householdId;if(!hid)return;const h=await db.collection('households').doc(hid).get(),o=h.data()?.mealOverrides;if(o&&typeof o==='object'){save(o);applyOverrides();window.R42_SHOPPING_V2?.render?.()}}catch(e){console.warn('Rome42 meal override load',e)}}
function choose(day,card){const part=card.dataset.part,current=card.dataset.code,choices=suggestions(current,part);let modal=document.getElementById('r42-swap-modal');if(!modal){modal=document.createElement('div');modal.id='r42-swap-modal';modal.style.cssText='position:fixed;inset:0;z-index:100000;background:rgba(35,18,18,.55);display:grid;place-items:end center;padding:18px';document.body.appendChild(modal)}modal.innerHTML=`<div class="card" style="width:min(100%,520px);max-height:78vh;overflow:auto;margin:0"><span class="tag">REMPLACER</span><h2>Choisir une autre recette</h2><p class="muted small">La liste de courses sera recalculée automatiquement.</p>${choices.map(c=>{const m=N().meal(c,part);return `<button class="btn secondary r42-choice" data-code="${c}" style="display:flex;align-items:center;gap:12px;text-align:left;margin:.6rem 0;width:100%"><img src="${m.photo}" alt="" style="width:72px;height:58px;border-radius:10px;object-fit:cover"><span><b>${esc(m.name)}</b><small style="display:block">${esc(details(c,part))}</small></span></button>`}).join('')}<button class="btn" id="r42-swap-cancel">Annuler</button></div>`;modal.style.display='grid';modal.querySelector('#r42-swap-cancel').onclick=()=>modal.style.display='none';modal.querySelectorAll('.r42-choice').forEach(b=>b.onclick=async()=>{const code=b.dataset.code,o=read();o[slotFor(day,part)]=code;save(o);applyCard(card,code);modal.style.display='none';window.R42_SHOPPING_V2?.render?.();document.dispatchEvent(new CustomEvent('r42:meal-swapped'));await cloudSave(o)})}
function decorate(){installExtras();applyOverrides();document.querySelectorAll('#nutrition .menu-day').forEach(day=>day.querySelectorAll('.recipe-open[data-part]').forEach(card=>{if(card.querySelector('.r42-swap'))return;const b=document.createElement('button');b.type='button';b.className='mini r42-swap';b.textContent='Changer';b.style.cssText='margin:8px 10px 10px;position:relative;z-index:2';b.onclick=e=>{e.preventDefault();e.stopPropagation();choose(day,card)};card.appendChild(b)}));window.R42_SHOPPING_V2?.render?.()}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(decorate,180)}).observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('click',e=>{if(e.target?.closest('nav button[data-v="nutrition"]'))setTimeout(()=>{decorate();cloudLoad()},350)});setTimeout(()=>{decorate();cloudLoad()},1800);
window.R42_MEAL_SWAP={decorate,applyOverrides,cloudLoad};
})();