(()=>{
const K='rome42-v1';
const q=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(K)||'{"days":{}}')}catch{return{days:{}}}};
const dateKey=()=>new Date().toLocaleDateString('sv-SE');
const minutes=t=>{const x=String(t||'').toLowerCase();let n=0,m=x.match(/(\d+)\s*h(?:\s*(\d+))?/);if(m)n+=(+m[1]*60)+(+m[2]||0);const mm=[...x.matchAll(/(\d+)\s*min/g)];if(mm.length&&!m)n+=Math.max(...mm.map(v=>+v[1]));return n};
const runRatio=t=>{const x=String(t||'').toLowerCase();let m=x.match(/(\d+)\s*min\s*(?:course)?\s*\/\s*(\d+)\s*min/);if(m)return +m[1]/(+m[1]+ +m[2]);m=x.match(/(\d+)\s*s\s*(?:course)?\s*\/\s*(\d+)\s*min\s*(\d+)?/);if(m){const a=+m[1]/60,b=+m[2]+(+m[3]||0)/100;return a/(a+b)};return /run\/walk|course|fartlek|fraction|endurance|sortie longue|marathon/.test(x)?1:0};
const kmFor=t=>{const x=String(t||'').toLowerCase();const direct=x.match(/(\d+(?:[,.]\d+)?)\s*km/);if(direct)return parseFloat(direct[1].replace(',','.'));const min=minutes(x),r=runRatio(x);return min&&r?min*r/6.5:0};
function plan(){try{return typeof window.plan==='function'?window.plan():window.APP_DATA?.weeks||[]}catch{return window.APP_DATA?.weeks||[]}}
function flat(){return plan().flatMap(w=>(w.days||[]).map(d=>({...d,week:w.week,phase:w.phase})))}
function stats(){const S=read(),days=flat(),done=days.filter(d=>S.days?.[d.date]?.done),km=done.reduce((a,d)=>a+kmFor(d.training),0);const weekMap=new Map;for(const d of days){if(!weekMap.has(d.week))weekMap.set(d.week,[]);weekMap.get(d.week).push(d)}let complete=0,best=0,streak=0;for(const [,ds] of weekMap){const planned=ds.filter(d=>!/repos complet/i.test(d.training||''));const ok=planned.length&&planned.every(d=>S.days?.[d.date]?.done);if(ok){complete++;streak++;best=Math.max(best,streak)}else streak=0}const today=dateKey(),future=days.filter(d=>d.date>=today);const key=future.find(d=>/sortie longue|fraction|fartlek|tempo|seuil|allure|marathon/i.test(d.training||''));return{done,km,complete,best,key,total:days.length};}
function milestone(km){const marks=[50,100,250,500,750,1000,1500];const next=marks.find(x=>x>km)||Math.ceil((km+1)/500)*500;const prev=[...marks].reverse().find(x=>x<=km)||0;return{next,prev,pct:Math.max(0,Math.min(100,(km-prev)/(next-prev)*100))}}
function phrase(s){if(s.km>=500)return`${Math.round(s.km)} km déjà construits. Ce volume n’est pas un badge : c’est du travail accumulé.`;if(s.complete>=4)return`${s.complete} semaines menées jusqu’au bout. La régularité construit ton marathon.`;if(s.done.length)return`${s.done.length} séances réalisées. Chaque sortie ajoute une pièce au projet Rome.`;return'Le chemin vers Rome commence par une séance, puis une autre.'}
function render(){const root=q('#progress');if(!root)return;root.querySelector('.journey-card')?.remove();const s=stats(),m=milestone(s.km),key=s.key;const card=document.createElement('div');card.className='card journey-card';card.innerHTML=`<div class="journey-head"><div><small class="journey-kicker">ROAD TO ROME</small><h2>Ton chemin vers Rome</h2></div><span class="journey-mark">R</span></div><p class="journey-lead">${esc(phrase(s))}</p><div class="journey-distance"><strong>${Math.round(s.km)}</strong><span>km parcourus depuis le début</span></div><div class="journey-track"><span style="width:${m.pct}%"></span></div><div class="journey-track-label"><span>${m.prev} km</span><b>prochaine étape · ${m.next} km</b></div><div class="journey-grid"><div><strong>${s.complete}</strong><span>semaines complètes</span></div><div><strong>${s.best}</strong><span>meilleure série</span></div></div>${key?`<div class="journey-next"><small>PROCHAINE ÉTAPE IMPORTANTE</small><b>Semaine ${key.week} · ${esc(key.training)}</b><span>${new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(key.date+'T12:00:00'))}</span></div>`:''}`;root.prepend(card)}
function celebrate(){const S=read(),d=flat().find(x=>x.date===dateKey());if(!d||!S.days?.[d.date]?.done||!/sortie longue|fraction|fartlek|tempo|seuil|allure|marathon/i.test(d.training||''))return;const k='r42-celebrated-'+d.date;if(sessionStorage.getItem(k))return;sessionStorage.setItem(k,'1');const toast=document.createElement('div');toast.className='rome-toast';toast.innerHTML='<small>ÉTAPE FRANCHIE</small><b>Séance clé terminée.</b><span>Tu viens d’ajouter une vraie brique à ta préparation pour Rome.</span>';document.body.appendChild(toast);setTimeout(()=>toast.classList.add('show'),30);setTimeout(()=>{toast.classList.remove('show');setTimeout(()=>toast.remove(),400)},4200)}
const mo=new MutationObserver(()=>{if(q('#progress')?.classList.contains('active'))requestAnimationFrame(render)});mo.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest?.('#done'))setTimeout(()=>{celebrate();render()},120);if(e.target.closest?.('nav button[data-v="progress"]'))setTimeout(render,80)},true);setTimeout(()=>{render();celebrate()},500);window.R42_MOTIVATION={render,stats};
})();