(()=>{const photos={A:{lunch:'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80'},B:{lunch:'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80'},C:{lunch:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80'},D:{lunch:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80'},F:{lunch:'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80'},G:{lunch:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',dinner:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80'}};
const lib={
A:{lunch:{name:'Poulet, riz & légumes',ingredients:[['Poulet',250,'g','Protéines'],['Riz',250,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Skyr',250,'g','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},dinner:{name:'Saumon, pommes de terre & légumes',ingredients:[['Saumon',220,'g','Poisson'],['Pommes de terre',350,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Huile d’olive',10,'g','Épicerie'],['Fromage blanc',200,'g','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},snack:[['Skyr',250,'g','Produits frais'],['Banane',1,'pièce','Fruits & légumes'],['Amandes',20,'g','Épicerie']]},
B:{lunch:{name:'Bœuf tomate & pâtes',ingredients:[['Bœuf haché 5 %',220,'g','Protéines'],['Pâtes',280,'g','Féculents'],['Sauce tomate',200,'g','Épicerie'],['Légumes variés',300,'g','Fruits & légumes'],['Huile d’olive',10,'g','Épicerie'],['Fruit',1,'pièce','Fruits & légumes']]},dinner:{name:'Omelette aux légumes & pain complet',ingredients:[['Œufs',4,'pièce','Produits frais'],['Blancs d’œufs',200,'g','Produits frais'],['Légumes variés',350,'g','Fruits & légumes'],['Pain complet',120,'g','Boulangerie'],['Fromage blanc',250,'g','Produits frais']]},snack:[['Skyr',250,'g','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},
C:{lunch:{name:'Dinde, semoule & légumes',ingredients:[['Dinde',250,'g','Protéines'],['Semoule',280,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Yaourt nature',1,'pot','Produits frais'],['Fruit',1,'pièce','Fruits & légumes']]},dinner:{name:'Cabillaud, riz & courgettes',ingredients:[['Cabillaud',280,'g','Poisson'],['Riz',250,'g','Féculents'],['Courgettes',400,'g','Fruits & légumes'],['Huile d’olive',10,'g','Épicerie'],['Fromage blanc',250,'g','Produits frais']]},snack:[['Skyr',250,'g','Produits frais'],['Noix',25,'g','Épicerie']]},
D:{lunch:{name:'Chili bœuf & haricots rouges',ingredients:[['Bœuf haché 5 %',220,'g','Protéines'],['Haricots rouges',180,'g','Épicerie'],['Riz',220,'g','Féculents'],['Tomates / poivrons / oignons',300,'g','Fruits & légumes'],['Huile d’olive',10,'g','Épicerie'],['Fruit',1,'pièce','Fruits & légumes']]},dinner:{name:'Poulet, pommes de terre & légumes',ingredients:[['Poulet',250,'g','Protéines'],['Pommes de terre',400,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Skyr',250,'g','Produits frais']]},snack:[['Banane',1,'pièce','Fruits & légumes'],['Fromage blanc',250,'g','Produits frais']]},
F:{lunch:{name:'Poulet curry coco & riz',ingredients:[['Poulet',250,'g','Protéines'],['Riz',300,'g','Féculents'],['Légumes variés',300,'g','Fruits & légumes'],['Lait de coco léger',100,'ml','Épicerie'],['Curry',1,'à prévoir','Épicerie'],['Fruit',1,'pièce','Fruits & légumes']]},dinner:{name:'Poisson blanc, pâtes & légumes',ingredients:[['Poisson blanc',280,'g','Poisson'],['Pâtes',300,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Huile d’olive',15,'g','Épicerie'],['Parmesan',20,'g','Produits frais'],['Skyr',200,'g','Produits frais']]},snack:[['Banane',1,'pièce','Fruits & légumes'],['Skyr',250,'g','Produits frais'],['Noix',20,'g','Épicerie']]},
G:{lunch:{name:'Poulet, pâtes tomate & parmesan',ingredients:[['Poulet',250,'g','Protéines'],['Pâtes',350,'g','Féculents'],['Sauce tomate',200,'g','Épicerie'],['Parmesan',25,'g','Produits frais'],['Légumes variés',300,'g','Fruits & légumes'],['Fruit',1,'pièce','Fruits & légumes']]},dinner:{name:'Saumon, riz & légumes',ingredients:[['Saumon',220,'g','Poisson'],['Riz',300,'g','Féculents'],['Légumes variés',350,'g','Fruits & légumes'],['Skyr',250,'g','Produits frais']]},snack:[['Banane',2,'pièce','Fruits & légumes'],['Skyr',250,'g','Produits frais'],['Pain complet',2,'tranche','Boulangerie'],['Miel',1,'à prévoir','Épicerie']]}}
function meal(code,part){const x=lib[code]||lib.C;return {...x[part],photo:photos[code]?.[part]||photos.C[part]}}
function aggregate(days,people){const out={};for(const d of days){const code=d.menu||'C',x=lib[code]||lib.C;const rows=[...x.lunch.ingredients,...x.dinner.ingredients,...x.snack];for(const [name,qty,unit,cat] of rows){const k=[name,unit,cat].join('|');if(!out[k])out[k]={name,qty:0,unit,cat};if(typeof qty==='number')out[k].qty+=qty*people;}}
return Object.values(out).sort((a,b)=>a.cat.localeCompare(b.cat)||a.name.localeCompare(b.name))}
function fmtQty(x){if(x.unit==='g'&&x.qty>=1000)return (x.qty/1000).toFixed(x.qty%1000?1:0).replace('.',',')+' kg';if(x.unit==='ml'&&x.qty>=1000)return (x.qty/1000).toFixed(x.qty%1000?1:0).replace('.',',')+' L';return `${Math.round(x.qty*10)/10} ${x.unit}`}
window.R42_NUTRITION={lib,photos,meal,aggregate,fmtQty};})();