(()=>{
const N=()=>window.R42_NUTRITION, NP=()=>window.R42_NUTRITION_PROFILE, H=()=>window.R42_HOUSEHOLD;
const BASE={A:2650,B:2650,C:2600,D:2700,F:2750,G:2850};
const RAW_FACTORS={
  'riz':0.40,
  'pâtes':0.45,
  'semoule':0.40
};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(q,u){if(u==='g'&&q>=1000)return(q/1000).toFixed(1).replace('.0','').replace('.',',')+' kg';if(u==='ml'&&q>=1000)return(q/1000).toFixed(1).replace('.0','').replace('.',',')+' L';return`${Math.max(1,Math.round(q*10)/10)} ${u}`}
function replacement(name,p){let n=name,l=name.toLowerCase();if(p?.diet==='vegetarian'&&(l.includes('poulet')||l.includes('dinde')||l.includes('bœuf')||l.includes('saumon')||l.includes('cabillaud')||l.includes('poisson')))n='Tofu ferme / légumineuses';else if(p?.diet==='pescatarian'&&(l.includes('poulet')||l.includes('dinde')||l.includes('bœuf')))n='Poisson / œufs';if(p?.dairyFree&&(l.includes('skyr')||l.includes('fromage blanc')||l.includes('yaourt')||l.includes('parmesan')))n='Alternative végétale enrichie';if(p?.glutenFree&&(l.includes('pâtes')||l.includes('semoule')||l.includes('pain')))n=l.includes('pain')?'Pain sans gluten':'Riz / pommes de terre';const banned=((p?.allergies||'')+','+(p?.exclusions||'')).toLowerCase().split(',').map(x=>x.trim()).filter(Boolean);if(banned.some(x=>l.includes(x)))return null;return n}
function childEER(p){const age=+p.age,h=+p.heightCm,w=+p.weightKg;if(!(age>=3&&age<19&&h>0&&w>0&&['male','female'].includes(p.sex)))return null;const hm=h/100;const activity=p.activityLevel||'low';const paM={sedentary:1,low:1.13,active:1.26,very:1.42};const paF={sedentary:1,low:1.16,active:1.31,very:1.56};const pa=(p.sex==='male'?paM:paF)[activity]||(p.sex==='male'?1.13:1.16);const eer=p.sex==='male'?88.5-(61.9*age)+pa*((26.7*w)+(903*hm))+25:135.3-(30.8*age)+pa*((10*w)+(934*hm))+25;return Math.max(1200,Math.round(eer/50)*50)}
function energy(person){const age=+person?.age;if(age>0&&age<18)return childEER(person);const e=NP()?.estimate?.(person);return e?.target||null}
function scale(person,code){const kcal=energy(person);return kcal?Math.max(.55,Math.min(1.45,kcal/(BASE[code]||2700))):null}
function people(){const own=NP()?.read?.();const others=H()?.members?.()||[];return [own,...others].filter(Boolean).map((p,i)=>({...p,_label:p.name||p.email||(i===0?'Mon profil':'Profil')})).filter(p=>scale(p,'C')!==null)}
function visibleDays(){return [...document.querySelectorAll('#nutrition .menu-day')].map(d=>d.querySelector('.recipe-open[data-code]')?.dataset.code).filter(Boolean)}
function rawInfo(name,qty,unit){if(unit!=='g')return{name,qty,unit,raw:false};const key=name.toLowerCase();for(const [k,f] of Object.entries(RAW_FACTORS)){if(key===k||key.startsWith(k+' ')||key.includes(k)){return{name:`${name} (poids cru estimé)`,qty:qty*f,unit,raw:true}}}return{name,qty,unit,raw:false}}
function aggregate(){const lib=N()?.lib,days=visibleDays(),persons=people(),out={};if(!lib||!days.length)return{rows:[],persons};for(const person of persons){for(const code of days){const x=lib[code]||lib.C,f=scale(person,code);if(!f)continue;for(const [name0,q,u,cat] of [...x.lunch.ingredients,...x.dinner.ingredients,...x.snack]){if(typeof q!=='number')continue;const replaced=replacement(name0,person);if(!replaced)continue;const r=rawInfo(replaced,q*f,u),k=[r.name,r.unit,cat].join('|');if(!out[k])out[k]={name:r.name,qty:0,unit:r.unit,cat,breakdown:{},raw:r.raw};out[k].qty+=r.qty;out[k].breakdown[person._label]=(out[k].breakdown[person._label]||0)+r.qty}}}return{rows:Object.values(out).sort((a,b)=>a.cat.localeCompare(b.cat)||a.name.localeCompare(b.name)),persons}}
function render(){const box=document.querySelector('#nutrition');if(!box||!box.classList.contains('active'))return;const cards=[...box.querySelectorAll('.card')],card=cards.find(c=>c.querySelector('.tag')?.textContent.trim()==='COURSES');if(!card)return;const {rows,persons}=aggregate();if(!rows.length)return;const cats={};rows.forEach(r=>(cats[r.cat]??=[]).push(r));const minors=persons.filter(p=>+p.age>0&&+p.age<18);card.id='r42-shopping-v2';card.innerHTML=`<span class="tag">COURSES</span><h2>Liste de courses du foyer</h2><p class="muted small"><b>${persons.length}</b> profil(s) pris en compte. Riz, pâtes et semoule sont affichés en <b>poids cru estimé</b> ; les recettes restent en poids de portion servi.</p>${minors.length?`<p class="muted small">Mineurs : objectif maintien. L’estimation utilise âge, taille, poids et sexe. Niveau d’activité utilisé : <b>${minors.some(p=>!p.activityLevel)?'faiblement actif par défaut pour les profils sans niveau renseigné':'celui du profil'}</b>.</p>`:''}${Object.entries(cats).map(([cat,items])=>`<div class="shop-cat"><h4>${esc(cat)}</h4>${items.map(x=>`<div class="checkline" style="align-items:flex-start"><input type="checkbox"><span style="flex:1"><b>${esc(x.name)}</b><small style="display:block;margin-top:.2rem">${Object.entries(x.breakdown).map(([n,q])=>`${esc(n)} : ${fmt(q,x.unit)}`).join(' · ')}</small></span><b>${fmt(x.qty,x.unit)}</b></div>`).join('')}</div>`).join('')}<button class="btn secondary" id="copyShop">Copier la liste</button>`;const b=card.querySelector('#copyShop');if(b)b.onclick=async()=>{const txt=rows.map(x=>`${x.name} : ${fmt(x.qty,x.unit)}`).join('\n');try{await navigator.clipboard.writeText(txt);b.textContent='Liste copiée ✓'}catch{b.textContent='Copie impossible'}}}
let t;const obs=new MutationObserver(()=>{clearTimeout(t);t=setTimeout(render,250)});obs.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('change',e=>{if(e.target?.closest('#nutrition'))setTimeout(render,100)});document.addEventListener('click',e=>{if(e.target?.closest('nav button[data-v="nutrition"]'))setTimeout(render,350)});setTimeout(render,1800);
window.R42_SHOPPING_V2={render,childEER};
})();