(()=>{
'use strict';
const CFG_KEY='rome42-settings-v1',STATE_KEY='rome42-v1';
const q=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readJson=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??fallback}catch{return fallback}};
const cfg=()=>readJson(CFG_KEY,{});
const backend=()=>String(cfg().stravaBackend||'').trim().replace(/\/$/,'');
const user=()=>window.R42_CLOUD?.currentUser?.()||null;
let status={known:false,connected:false,error:'',checkedAt:0},statusPromise=null,raf=false;
function ensureStyle(){if(q('#r42-strava-style'))return;const s=document.createElement('style');s.id='r42-strava-style';s.textContent=`
.r42-strava-status{display:flex;align-items:center;gap:8px;margin:.8rem 0}.r42-strava-dot{width:9px;height:9px;border-radius:50%;background:#aaa}.r42-strava-status.on .r42-strava-dot{background:#27854a}.r42-strava-status.wait .r42-strava-dot{background:#c18b26}.r42-strava-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.r42-strava-dev{margin-top:14px;border-top:1px solid rgba(91,65,50,.12);padding-top:12px}.r42-strava-dev summary{cursor:pointer;font-weight:800;color:#751e2a}.r42-strava-candidates{display:grid;gap:9px;margin-top:12px}.r42-strava-activity{border:1px solid rgba(117,30,42,.13);border-radius:16px;padding:12px;background:#fffaf4}.r42-strava-activity.recommended{border-color:rgba(117,30,42,.35);box-shadow:0 7px 22px rgba(76,37,31,.08)}.r42-strava-activity-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.r42-strava-activity small{display:block;color:#78665d;margin-top:4px;line-height:1.35}.r42-strava-link{display:inline-block;margin-top:7px;font-size:.78rem;font-weight:800;text-decoration:underline}.r42-strava-match{margin-top:9px;width:100%}.r42-strava-note{font-size:.76rem;color:#78665d;line-height:1.4;margin-top:10px}.r42-strava-imported{background:#eef7f0;border:1px solid rgba(38,125,71,.18);border-radius:14px;padding:11px 12px;margin-top:10px}.r42-strava-toast{position:fixed;left:50%;bottom:92px;transform:translate(-50%,12px);z-index:100070;background:#39221e;color:#fff;padding:10px 14px;border-radius:999px;font-size:.82rem;font-weight:800;opacity:0;pointer-events:none;transition:.2s}.r42-strava-toast.show{opacity:1;transform:translate(-50%,0)}@media(max-width:430px){.r42-strava-actions{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function toast(text){let t=q('#r42StravaToast');if(!t){t=document.createElement('div');t.id='r42StravaToast';t.className='r42-strava-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)}
function removeGarmin(){const root=q('#settings');if(!root)return;[...root.children].forEach(el=>{if(/garmin connect/i.test(el.textContent||''))el.remove()})}
function saveBackend(value){const c=cfg();c.stravaBackend=String(value||'').trim().replace(/\/$/,'');localStorage.setItem(CFG_KEY,JSON.stringify(c));status={known:false,connected:false,error:'',checkedAt:0};location.reload()}
async function api(path,opts={}){const b=backend(),u=user();if(!b)throw Error('Connecteur Strava non configuré.');if(!u)throw Error('Compte Rome42 requis.');const token=await u.getIdToken();const headers={...(opts.headers||{}),Authorization:`Bearer ${token}`};if(opts.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const res=await fetch(b+path,{...opts,headers});let data=null;try{data=await res.json()}catch{}if(!res.ok)throw Error(data?.error||`Erreur Strava (${res.status})`);return data}
async function refreshStatus(force=false){if(!backend()||!user()){status={known:true,connected:false,error:'',checkedAt:Date.now()};return status}if(!force&&status.known&&Date.now()-status.checkedAt<60000)return status;if(statusPromise)return statusPromise;statusPromise=api('/api/strava/status').then(x=>status={known:true,connected:!!x.connected,error:'',checkedAt:Date.now()}).catch(e=>status={known:true,connected:false,error:e.message,checkedAt:Date.now()}).finally(()=>statusPromise=null);return statusPromise}
function cardMarkup(){const b=backend();if(!b)return `<span class="tag">ACTIVITÉS</span><h2>Strava</h2><p class="muted">Rome42 peut associer une activité Strava à la séance prévue, sans conserver dans ton suivi les données détaillées de l’activité.</p><div class="r42-strava-status wait"><span class="r42-strava-dot"></span><b>Connecteur à déployer</b></div><p class="muted small">La partie application est prête. Il reste à déployer le petit connecteur sécurisé Cloudflare Worker puis à renseigner son adresse une seule fois.</p><details class="r42-strava-dev" open><summary>Configuration développeur</summary><label>URL du Worker Rome42 Strava</label><input id="r42StravaBackend" placeholder="https://rome42-strava…workers.dev"><button class="btn secondary" id="r42SaveStravaBackend">Enregistrer le connecteur</button></details>`;
if(!status.known)return `<span class="tag">ACTIVITÉS</span><h2>Strava</h2><p class="muted">Connexion sécurisée à tes activités pour valider plus facilement les séances Rome42.</p><div class="r42-strava-status wait"><span class="r42-strava-dot"></span><b>Vérification…</b></div>`;
if(status.connected)return `<span class="tag">ACTIVITÉS</span><h2>Strava</h2><p class="muted">Tes activités restent chez Strava. Rome42 les consulte au moment où tu demandes une association avec une séance.</p><div class="r42-strava-status on"><span class="r42-strava-dot"></span><b>Strava connecté</b></div><div class="r42-strava-actions"><button class="btn" id="r42StravaFind">Trouver mon activité</button><button class="btn secondary" id="r42StravaDisconnect">Déconnecter Strava</button></div><p class="r42-strava-note">Après association, Rome42 mémorise seulement que la séance a été validée via Strava. Distance, allure et détail de l’activité ne sont pas conservés dans l’historique Rome42.</p><details class="r42-strava-dev"><summary>Configuration développeur</summary><label>URL du Worker Rome42 Strava</label><input id="r42StravaBackend" value="${esc(b)}"><button class="btn secondary" id="r42SaveStravaBackend">Mettre à jour</button></details>`;
return `<span class="tag">ACTIVITÉS</span><h2>Strava</h2><p class="muted">Associe tes sorties enregistrées sur Strava aux séances Rome42.</p><div class="r42-strava-status ${status.error?'wait':''}"><span class="r42-strava-dot"></span><b>${status.error?'Connecteur indisponible':'Non connecté'}</b></div>${status.error?`<p class="muted small">${esc(status.error)}</p>`:''}<button class="btn" id="r42StravaConnect">Connecter Strava</button><details class="r42-strava-dev"><summary>Configuration développeur</summary><label>URL du Worker Rome42 Strava</label><input id="r42StravaBackend" value="${esc(b)}"><button class="btn secondary" id="r42SaveStravaBackend">Mettre à jour</button></details>`}
function bindSettings(card){q('#r42SaveStravaBackend',card)?.addEventListener('click',()=>saveBackend(q('#r42StravaBackend',card)?.value));q('#r42StravaConnect',card)?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Ouverture de Strava…';try{const ret=location.origin+location.pathname,data=await api('/api/strava/connect-url?return='+encodeURIComponent(ret));location.href=data.url}catch(err){toast(err.message);b.disabled=false;b.textContent='Connecter Strava'}});q('#r42StravaDisconnect',card)?.addEventListener('click',async e=>{if(!confirm('Déconnecter Strava de Rome42 ?'))return;const b=e.currentTarget;b.disabled=true;try{await api('/api/strava/disconnect',{method:'POST'});status={known:true,connected:false,error:'',checkedAt:Date.now()};renderAll()}catch(err){toast(err.message);b.disabled=false}});q('#r42StravaFind',card)?.addEventListener('click',()=>{document.querySelector('nav button[data-v="today"]')?.click();setTimeout(()=>q('#r42StravaTodayFind')?.click(),180)})}
function settingsCard(){const root=q('#settings');if(!root)return;removeGarmin();let card=q('#r42-strava',root);if(!card){card=document.createElement('section');card.id='r42-strava';card.className='card';root.appendChild(card)}const sig=[backend(),status.known,status.connected,status.error].join('|');if(card.dataset.sig===sig)return;card.dataset.sig=sig;card.innerHTML=cardMarkup();bindSettings(card)}
function currentDay(){try{if(typeof cur==='function')return cur()}catch{}return null}
function dayState(day){return readJson(STATE_KEY,{days:{},weights:[]})?.days?.[day?.date]||{}}
function trainingDuration(text=''){const s=String(text);let m=s.match(/(\d+)\s*[–-]\s*(\d+)\s*min/i);if(m)return{min:+m[1],max:+m[2]};m=s.match(/(\d+)\s*min/i);return m?{min:+m[1],max:+m[1]}:null}
function activityTypeOk(a,training=''){const sport=(a.sport_type||a.type||'').toLowerCase(),t=training.toLowerCase();if(t.includes('marche')&&!t.includes('course/'))return sport.includes('walk')||sport.includes('run');return sport.includes('run')||sport.includes('walk')}
function scoreActivity(a,day){let s=0;const local=String(a.start_date_local||'').slice(0,10);if(local===day.date)s+=100;if(activityTypeOk(a,day.training))s+=30;const d=trainingDuration(day.training),mins=(+a.moving_time||0)/60;if(d){if(mins>=d.min-3&&mins<=d.max+3)s+=30;else{s-=Math.min(25,Math.abs(mins-((d.min+d.max)/2))/2)}}return s}
function pace(a){const speed=+a.average_speed||0;if(!speed)return'';const sec=Math.round(1000/speed),m=Math.floor(sec/60),s=String(sec%60).padStart(2,'0');return `${m}:${s}/km`}
function fmtActivity(a){const km=(+a.distance||0)/1000,mins=Math.round((+a.moving_time||0)/60),p=pace(a);return `${km?km.toFixed(2).replace('.',',')+' km · ':''}${mins} min${p?' · '+p:''}`}
function todayBaseMarkup(day,stateDay){if(stateDay.completedVia==='strava')return `<span class="tag">STRAVA</span><h3>Séance associée ✓</h3><div class="r42-strava-imported"><b>Cette séance a été validée via une activité Strava.</b><p class="muted small">Les détails Strava ne sont pas conservés dans l’historique Rome42. Tu peux compléter ton RPE, tes douleurs et ton commentaire dans le compte-rendu.</p></div>`;return `<span class="tag">STRAVA</span><h3>Retrouver ma sortie</h3><p class="muted small">Rome42 cherche uniquement quand tu le demandes parmi tes activités récentes et te propose la meilleure correspondance avec la séance prévue.</p><button class="btn secondary" id="r42StravaTodayFind">Rechercher mon activité Strava</button><div id="r42StravaCandidates"></div>`}
function todayCard(){const root=q('#today');if(!root)return;let card=q('#r42-strava-today',root);if(!backend()||!status.connected){card?.remove();return}const day=currentDay();if(!day)return;const st=dayState(day);if(!card){card=document.createElement('section');card.id='r42-strava-today';card.className='card';const report=[...root.querySelectorAll('.card')].find(x=>/compte-rendu/i.test(x.textContent||''));report?.insertAdjacentElement('afterend',card)||root.appendChild(card)}const sig=day.date+'|'+(st.completedVia||'');if(card.dataset.sig===sig)return;card.dataset.sig=sig;card.innerHTML=todayBaseMarkup(day,st);q('#r42StravaTodayFind',card)?.addEventListener('click',()=>loadActivities(card,day))}
async function loadActivities(card,day){const btn=q('#r42StravaTodayFind',card),box=q('#r42StravaCandidates',card);if(!box)return;if(btn){btn.disabled=true;btn.textContent='Recherche en cours…'}box.innerHTML='';try{const start=new Date(day.date+'T00:00:00'),after=Math.floor((start.getTime()-86400000)/1000),before=Math.floor((start.getTime()+2*86400000)/1000),data=await api(`/api/strava/activities?after=${after}&before=${before}&per_page=20`),all=(data.activities||[]).filter(a=>activityTypeOk(a,day.training)).sort((a,b)=>scoreActivity(b,day)-scoreActivity(a,day)).slice(0,5);if(!all.length){box.innerHTML='<p class="muted small">Aucune activité course/marche trouvée autour de cette séance.</p>';return}box.innerHTML=`<div class="r42-strava-candidates">${all.map((a,i)=>`<div class="r42-strava-activity ${i===0?'recommended':''}" data-activity="${String(a.id)}"><div class="r42-strava-activity-head"><div><b>${esc(a.name||'Activité Strava')}</b><small>${esc(fmtActivity(a))}<br>${esc(new Date(a.start_date_local||a.start_date).toLocaleString('fr-FR',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</small></div>${i===0?'<span class="tag">MEILLEURE CORRESPONDANCE</span>':''}</div><a class="r42-strava-link" href="${esc(a.strava_url)}" target="_blank" rel="noopener noreferrer">View on Strava</a><button class="btn secondary r42-strava-match" data-match="${String(a.id)}">Associer à cette séance</button></div>`).join('')}</div><p class="r42-strava-note">L’association valide la séance. Les données détaillées affichées ici ne sont pas enregistrées dans Rome42.</p>`;box.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>matchActivity(day,b.dataset.match,all))}catch(err){box.innerHTML=`<p class="muted small">${esc(err.message)}</p>`}finally{if(btn){btn.disabled=false;btn.textContent='Rechercher à nouveau'}}}
function matchActivity(day,id,activities){const a=activities.find(x=>String(x.id)===String(id));if(!a)return;const state=readJson(STATE_KEY,{days:{},weights:[]});state.days=state.days||{};const prev=state.days[day.date]||{};state.days[day.date]={...prev,done:true,completedVia:'strava',stravaMatchedAt:new Date().toISOString()};localStorage.setItem(STATE_KEY,JSON.stringify(state));toast('Séance associée et validée ✓');setTimeout(()=>location.reload(),450)}
async function renderAll(){ensureStyle();settingsCard();todayCard()}
function schedule(){if(raf)return;raf=true;requestAnimationFrame(()=>{raf=false;renderAll()})}
const obs=new MutationObserver(schedule);const settings=q('#settings'),today=q('#today');if(settings)obs.observe(settings,{childList:true});if(today)obs.observe(today,{childList:true});document.addEventListener('click',e=>{if(e.target.closest?.('nav button[data-v="settings"],nav button[data-v="today"]'))setTimeout(async()=>{await refreshStatus();renderAll()},90)},true);window.addEventListener('pageshow',()=>setTimeout(async()=>{await refreshStatus();renderAll()},250));
const u=new URL(location.href);if(u.searchParams.get('strava')){const result=u.searchParams.get('strava');u.searchParams.delete('strava');history.replaceState({},'',u.pathname+(u.search||'')+u.hash);if(result==='connected')toast('Strava connecté ✓');if(result==='error')toast('Connexion Strava annulée ou impossible')}
setTimeout(async()=>{await refreshStatus();renderAll()},800);
window.R42_STRAVA={refreshStatus,findToday:()=>q('#r42StravaTodayFind')?.click(),disconnect:()=>q('#r42StravaDisconnect')?.click()};
})();