(()=>{
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function classify(t=''){const x=t.toLowerCase();if(/repos|récup|off/.test(x))return{icon:'◎',label:'Récupération',tone:'recovery'};if(/renfo|gainage|muscu/.test(x))return{icon:'◆',label:'Renforcement',tone:'strength'};if(/fraction|interval|tempo|seuil|allure|fartlek|côte/.test(x))return{icon:'⚡',label:'Séance qualité',tone:'quality'};if(/long|sortie longue/.test(x))return{icon:'↗',label:'Sortie longue',tone:'long'};return{icon:'→',label:'Endurance',tone:'easy'}}
function nutritionTip(t=''){const x=t.toLowerCase();if(/long|fraction|interval|tempo|seuil|allure|fartlek/.test(x))return['Énergie','Privilégie des glucides faciles à digérer avant la séance et teste ton ravitaillement prévu pour la course.'];if(/renfo|muscu/.test(x))return['Récupération','Répartis protéines et glucides sur la journée et hydrate-toi régulièrement.'];if(/repos|récup/.test(x))return['Journée légère','Garde des repas complets et réguliers, sans chercher à surcompenser la baisse de charge.'];return['Carburant','Repas équilibré, hydratation régulière et collation seulement si la faim ou l’horaire de séance le justifie.']}
function recoveryTip(r){const pain=Math.max(r?.knee||0,r?.ankle||0,r?.back||0,r?.shoulder||0);if(pain>=4)return['À surveiller','Une douleur ≥ 4/10 a été enregistrée. Évite d’augmenter la charge et fais évaluer une douleur persistante.'];if((r?.rpe||0)>=8)return['Récupération','Ta dernière perception d’effort était élevée. Priorise sommeil, hydratation et récupération facile.'];return['Récupération','Après la séance : quelques minutes au calme, hydratation et sommeil régulier.']}
function cleanMetric(el){const small=el.querySelector('small')?.textContent?.trim()||'',b=el.querySelector('b')?.textContent?.trim()||'';if(!b||/^(undefined|null|nan)$/i.test(b))return'';return `<div class="metric"><small>${esc(small)}</small><b>${esc(b)}</b></div>`}
function render(){const root=q('#today');if(!root||!root.classList.contains('active'))return;const oldHero=root.querySelector('.card:not(.danger):not(.alert)');if(!oldHero||oldHero.dataset.smartToday)return;const big=oldHero.querySelector('.big');if(!big)return;const training=big.textContent.trim(),tag=oldHero.querySelector('.tag')?.textContent||'',title=oldHero.querySelector('h2')?.textContent||'',metrics=[...oldHero.querySelectorAll('.metric')].map(cleanMetric).filter(Boolean).join('');const kind=classify(training);let report=[...root.querySelectorAll('.card')].find(c=>c.querySelector('#rpe'));const rpe=report?.querySelector('#rpe')?.value||'';const state={rpe:+rpe||0,knee:+report?.querySelector('#knee')?.value||0,ankle:+report?.querySelector('#ankle')?.value||0,back:+report?.querySelector('#back')?.value||0,shoulder:+report?.querySelector('#shoulder')?.value||0};const food=nutritionTip(training),rec=recoveryTip(state);
oldHero.dataset.smartToday='1';oldHero.classList.add('smart-today',`smart-${kind.tone}`);oldHero.innerHTML=`<div class="today-top"><div><span class="tag">${esc(tag)}</span><p class="today-date">${esc(title)}</p></div><span class="today-icon">${kind.icon}</span></div><small class="today-eyebrow">AUJOURD’HUI · ${kind.label.toUpperCase()}</small><div class="today-training">${esc(training)}</div><button class="btn today-cta" id="todayDetails">Voir le détail de la séance <span>→</span></button>${metrics?`<div class="today-metrics">${metrics}</div>`:''}`;
const info=document.createElement('div');info.className='today-brief';info.innerHTML=`<div class="today-brief-card"><span>◌</span><div><small>${food[0]}</small><b>${food[1]}</b></div></div><div class="today-brief-card"><span>☾</span><div><small>${rec[0]}</small><b>${rec[1]}</b></div></div>`;oldHero.insertAdjacentElement('afterend',info);
q('#todayDetails')?.addEventListener('click',()=>{const weekBtn=q('nav button[data-v="week"]');weekBtn?.click();setTimeout(()=>{const rows=[...q('#week')?.querySelectorAll('.row')||[]];const hit=rows.find(x=>x.textContent.includes(training));hit?.scrollIntoView({behavior:'smooth',block:'center'});hit?.click?.()},80)});
if(report){report.classList.add('today-report');const h=report.querySelector('h3');if(h&&!report.querySelector('.today-report-intro'))h.insertAdjacentHTML('afterend','<p class="today-report-intro">Après la séance, 20 secondes suffisent pour aider Rome42 à suivre ton ressenti.</p>')}
}
const mo=new MutationObserver(()=>requestAnimationFrame(render));mo.observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('click',e=>{if(e.target.closest?.('nav button[data-v="today"]'))setTimeout(render,30)},true);setTimeout(render,100);
})();