(()=>{
const glossary={RPE:'Effort perçu sur 10 : 1 très facile, 10 maximal.',EF:'Endurance fondamentale : allure facile, respiration confortable.',SL:'Sortie longue : séance d’endurance plus longue que les sorties habituelles.',VMA:'Vitesse maximale aérobie : repère utilisé pour calibrer certaines intensités.',FC:'Fréquence cardiaque.',PPG:'Préparation physique générale : renforcement, mobilité et gainage.',AS42:'Allure spécifique marathon, celle visée sur 42,195 km.',REC:'Récupération : effort volontairement très facile.'};
const encouragements=['Un entraînement régulier vaut mieux qu’une séance parfaite.','Aujourd’hui, l’objectif est simple : faire la séance prévue, pas davantage.','Chaque séance terminée construit Rome, une journée à la fois.','La constance fait le chrono. Garde de l’énergie pour demain.','Facile quand c’est facile, engagé quand c’est prévu : c’est ainsi qu’un plan fonctionne.'];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function details(t){let s=String(t||''),low=s.toLowerCase(),type=low.includes('repos')?'Récupération':low.includes('long')?'Sortie longue':low.includes('fraction')||low.includes('interval')||low.includes('vma')?'Qualité':low.includes('renfo')||low.includes('ppg')?'Renforcement':'Course';let warm=type==='Récupération'?'10–20 min de marche et mobilité douce.':'10–15 min très faciles + quelques mouvements dynamiques.';let core=s;let cool=type==='Récupération'?'Pas d’intensité aujourd’hui.':'5–10 min très faciles, puis hydratation et retour au calme.';let focus=type==='Sortie longue'?'Reste facile au début. Teste hydratation et ravitaillement comme le jour J.':type==='Qualité'?'Les répétitions doivent rester maîtrisées. Arrête la qualité si la foulée se dégrade.':type==='Renforcement'?'Priorité à la qualité des mouvements, jamais à la charge.':'Tu dois finir avec la sensation que tu aurais pu en faire un peu plus.';return{type,warm,core,cool,focus}}
function glossaryHtml(t){let keys=Object.keys(glossary).filter(k=>new RegExp('(^|[^A-Z0-9])'+k+'([^A-Z0-9]|$)','i').test(t||''));if(!keys.length)keys=['RPE'];return `<div class="ux-glossary"><h3>Repères utiles</h3>${keys.map(k=>`<details><summary>${k}</summary><p>${glossary[k]}</p></details>`).join('')}</div>`}
function openTraining(d){let x=details(d.training),done=window.S?.days?.[d.date]?.done;let modal=document.querySelector('#trainingDetail');if(!modal){modal=document.createElement('div');modal.id='trainingDetail';modal.className='training-modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="training-sheet"><button class="training-close" aria-label="Fermer">×</button><span class="tag">${esc(x.type)} · Semaine ${esc(d.week)}</span><h2>${esc(d.training)}</h2><p class="ux-coach">${encouragements[(d.week+new Date(d.date+'T12:00:00').getDay())%encouragements.length]}</p><div class="training-step"><small>1 · ÉCHAUFFEMENT</small><b>${esc(x.warm)}</b></div><div class="training-step main"><small>2 · SÉANCE</small><b>${esc(x.core)}</b></div><div class="training-step"><small>3 · RETOUR AU CALME</small><b>${esc(x.cool)}</b></div><div class="ux-tip"><b>Le point du coach</b><p>${esc(x.focus)}</p></div>${glossaryHtml(d.training)}<button class="btn training-to-today">${done?'Voir mon compte-rendu ✓':'Faire cette séance'}</button></div>`;modal.classList.add('open');modal.querySelector('.training-close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};modal.querySelector('.training-to-today').onclick=()=>{modal.classList.remove('open');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector('#today')?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}}
function visibleWeek(){if(typeof window.plan!=='function')return null;const box=document.querySelector('#week');const h=box?.querySelector('h2')?.textContent||'';const m=h.match(/Semaine\s+(\d+)/i);const n=m?+m[1]:null;const weeks=window.plan();return weeks.find(w=>w.week===n)||weeks[0]||null}
function decorate(){if(typeof window.cur!=='function')return;let d=window.cur();if(!d)return;let today=document.querySelector('#today');if(today&&!today.querySelector('.ux-daily')){let first=today.querySelector('.card');if(first){first.classList.add('ux-today-card');let n=document.createElement('div');n.className='ux-daily';n.innerHTML=`<div class="ux-eyebrow">TON CAP DU JOUR</div><p>${encouragements[(d.week+new Date(d.date+'T12:00:00').getDay())%encouragements.length]}</p><button class="ux-session-btn">Voir le programme de la séance <span>→</span></button>`;first.appendChild(n);n.querySelector('button').onclick=()=>openTraining(d)}}let week=document.querySelector('#week');if(week){const w=visibleWeek();week.querySelectorAll('.row').forEach((r,i)=>{const dd=w?.days?.[i];if(dd&&!r.classList.contains('ux-clickable')){r.classList.add('ux-clickable');r.setAttribute('role','button');r.setAttribute('tabindex','0');r.insertAdjacentHTML('beforeend','<span class="ux-row-arrow">Détails →</span>');r.onclick=()=>openTraining(dd);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openTraining(dd)}}}})}}
let obs=new MutationObserver(()=>requestAnimationFrame(decorate));obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('load',decorate);setTimeout(decorate,300);window.R42_UX={openTraining,glossary};
})();