(()=>{
const glossary={
RPE:'Effort perçu sur 10 : 1–2 très facile, 3–4 facile, 5 modéré, 6 soutenu, 7–8 difficile, 9–10 très difficile à maximal.',
FARTLEK:'« Jeu d’allures » : une séance de course qui alterne des passages plus rapides et des récupérations faciles. Ce n’est pas un sprint.',
EF:'Endurance fondamentale : course très confortable, à une intensité où la conversation reste possible.',
SL:'Sortie longue : séance d’endurance plus longue que les sorties habituelles, réalisée majoritairement à allure facile.',
VMA:'Vitesse maximale aérobie : repère utilisé pour calibrer certaines intensités courtes.',
FC:'Fréquence cardiaque.',
PPG:'Préparation physique générale : renforcement, mobilité et gainage.',
AS42:'Allure spécifique marathon : l’allure prévue pour le marathon, travaillée progressivement à l’entraînement.',
REC:'Récupération : effort volontairement très facile.',
'RUN/WALK':'Course/marche : alternance planifiée de course et de marche. Les phases de marche font partie de la stratégie.',
'ALLURE MARATHON':'Intensité correspondant à l’allure que le plan prévoit de tenir le jour du marathon.',
FRACTIONNÉ:'Séance structurée avec des portions rapides répétées et des récupérations entre chaque répétition.',
CÔTES:'Répétitions courues en montée pour travailler la force et la qualité de foulée, avec récupération facile en descente.'
};
const encouragements=['Un entraînement régulier vaut mieux qu’une séance parfaite.','Aujourd’hui, l’objectif est simple : faire la séance prévue, pas davantage.','Chaque séance terminée construit Rome, une journée à la fois.','La constance fait le chrono. Garde de l’énergie pour demain.','Facile quand c’est facile, engagé quand c’est prévu : c’est ainsi qu’un plan fonctionne.'];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function profileStrategy(){try{const p=JSON.parse(localStorage.getItem('rome42-profile-v2')||'null');return p?.mode==='custom'&&window.R42_ENGINE?.strategy?R42_ENGINE.strategy(p):null}catch{return null}}
function easyMode(){const st=profileStrategy();return st?.type==='runwalk'?'en course/marche selon ton alternance habituelle':'en footing très facile'}
function details(t){
 const s=String(t||''),low=s.toLowerCase(),st=profileStrategy();
 let x={type:'Course',activity:'Course à pied',objective:'Réaliser la séance prévue avec une intensité maîtrisée.',steps:[],focus:'Tu dois terminer en gardant de la marge.',terms:['RPE']};
 const fart=low.includes('fartlek'),hills=low.includes('côte'),fraction=low.includes('fraction'),specific=low.includes('spécifique marathon')||low.includes('allure marathon'),long=low.includes('sortie longue'),strength=low.includes('renforcement')||low.includes('ppg'),rest=low.startsWith('repos')||low.includes('repos complet'),recovery=low.includes('récupération')||low.includes('mobilité douce'),bike=low.includes('vtt'),walk=low.includes('marche')&&!low.includes('run/walk')&&!low.includes('course/marche');
 if(rest){x.type='Récupération';x.activity='Repos / mobilité';x.objective='Assimiler les séances précédentes sans ajouter de fatigue.';x.steps=[['AU PROGRAMME','Pas de course à pied. Si de la mobilité est indiquée, reste sur des mouvements doux et confortables.'],['INTENSITÉ','Aucun travail soutenu aujourd’hui. La séance doit te laisser plus frais, pas plus fatigué.']];x.focus='Le repos fait partie du plan : ne cherche pas à “rattraper” une séance difficile ce jour-là.';x.terms=['REC'];return x}
 if(strength){x.type='Renforcement';x.activity='Renforcement musculaire';x.objective='Améliorer la force utile à la course sans créer de fatigue résiduelle excessive.';x.steps=[['MISE EN ROUTE','Quelques minutes de mobilité dynamique : chevilles, hanches, genoux et épaules.'],['BLOC PRINCIPAL',s.replace(/^Renforcement[^:]*:?\s*/i,'')||s],['COMMENT LE FAIRE','Squat/fente = travail des jambes ; charnière de hanche = mouvement type soulevé de terre léger ; mollets, fessiers et gainage complètent le circuit. Respecte les 2–3 séries prévues et garde toujours une technique propre.'],['FIN DE SÉANCE','Arrête avant l’échec musculaire. Tu dois pouvoir courir normalement lors de la prochaine séance prévue.']];x.focus='La qualité des mouvements prime sur la charge ou le nombre de répétitions.';x.terms=['PPG'];return x}
 if(fart){const m=s.match(/(\d+)\s*[×x]\s*(\d+)\s*min[^/]*\/\s*(\d+)\s*min/i),n=m?.[1]||'6',fast=m?.[2]||'1',rec=m?.[3]||'2';x.type='Séance qualité';x.activity='Course à pied';x.objective='Apprendre à changer d’allure tout en restant relâché et contrôlé.';x.steps=[['1 · ÉCHAUFFEMENT',`15 min ${easyMode()}. « Facile » signifie une allure où tu peux parler en phrases complètes et où tu ne cherches pas la vitesse.`],['2 · FARTLEK',`${n} fois : ${fast} min de course soutenue, puis ${rec} min très faciles. La partie soutenue est nettement plus rapide que ton footing mais reste contrôlée ; ce n’est pas un sprint. Pendant la récupération, trottine très lentement ou marche si ta stratégie est en course/marche.`],['3 · RETOUR AU CALME',`Reviens ${easyMode()} jusqu’à retrouver une respiration calme. Ne termine pas la séance par une accélération.`]];x.focus='Le but est que la dernière répétition soit aussi propre que la première.';x.terms=['FARTLEK','RPE'];return x}
 if(hills){x.type='Séance qualité';x.activity='Course à pied · côtes';x.objective='Travailler la force de course et la qualité de foulée sans sprinter.';x.steps=[['1 · ÉCHAUFFEMENT',`15 min ${easyMode()}, puis quelques mouvements dynamiques de chevilles et de hanches.`],['2 · CÔTES',s.includes(':')?s.split(':').slice(1).join(':').trim():s],['COMMENT LIRE LA SÉANCE','Chaque répétition se court en montée à l’intensité indiquée. La récupération se fait en redescendant très doucement, en marchant ou en trottinant.'],['3 · RETOUR AU CALME',`Termine ${easyMode()} jusqu’à retrouver une respiration confortable.`]];x.focus='En côte, reste grand et relâché. L’intensité doit venir de l’effort, pas d’un sprint maximal.';x.terms=['CÔTES','RPE'];return x}
 if(fraction){x.type='Séance qualité';x.activity='Course à pied · fractionné';x.objective='Développer la capacité à courir plus vite par blocs contrôlés.';x.steps=[['1 · ÉCHAUFFEMENT','15–20 min de footing très facile. Il s’agit bien de course à pied, avec une allure volontairement lente.'],['2 · BLOC RAPIDE',s.includes(':')?s.split(':').slice(1).join(':').trim():s],['RÉCUPÉRATIONS','Entre les répétitions, la récupération « trot » signifie courir très lentement, sans chercher à maintenir l’allure rapide.'],['3 · RETOUR AU CALME','10–15 min de footing très facile pour faire redescendre progressivement l’effort.']];x.focus='Ne pars pas trop vite : les répétitions doivent rester régulières et maîtrisées.';x.terms=['FRACTIONNÉ','RPE'];return x}
 if(specific){x.type='Spécifique marathon';x.activity=st?.type==='runwalk'?'Course / marche':'Course à pied';x.objective='Apprendre à reconnaître et tenir l’effort prévu pour le marathon.';x.steps=[['1 · ÉCHAUFFEMENT',`Commence ${easyMode()} à une intensité très confortable.`],['2 · BLOC MARATHON',s.includes(':')?s.split(':').slice(1).join(':').trim():s],['RÉCUPÉRATION ENTRE BLOCS','Quand une récupération est indiquée, ralentis franchement : footing très lent ou marche active selon ta stratégie.'],['3 · RETOUR AU CALME',`Termine ${easyMode()} sans ajouter de kilomètres ou d’accélérations.`]];x.focus='L’allure marathon doit sembler contrôlée. Cette séance sert à apprendre le rythme, pas à tester tes limites.';x.terms=['ALLURE MARATHON','RPE'];if(st?.type==='runwalk')x.terms.push('RUN/WALK');return x}
 if(long){x.type='Sortie longue';x.activity=low.includes('run/walk')||low.includes('course/marche')||st?.type==='runwalk'?'Course / marche':'Course à pied';x.objective='Développer l’endurance et tester progressivement la stratégie prévue pour le marathon.';x.steps=[['1 · DÉPART','Les 10–15 premières minutes sont volontairement très faciles. Pars plus lentement que ce que ton énergie du moment pourrait te permettre.'],['2 · SÉANCE',s],['ALLURE','« Endurance facile · RPE 3–4 » = effort confortable, respiration maîtrisée, conversation possible. '+(st?.type==='runwalk'?'Applique l’alternance course/marche prévue dès le début, sans attendre d’être fatigué.':'Reste en course continue facile sauf indication contraire dans la séance.')],['RAVITAILLEMENT','Si le plan demande de tester hydratation ou nutrition, utilise uniquement ce qui est prévu et déjà toléré à l’entraînement.']];x.focus='Une sortie longue réussie n’est pas une course : le premier objectif est de finir encore capable de courir proprement.';x.terms=['SL','RPE'];if(st?.type==='runwalk')x.terms.push('RUN/WALK');return x}
 if(bike){x.type='Endurance croisée';x.activity=low.includes('marche')?'VTT ou marche active':'VTT';x.objective='Développer l’endurance avec moins d’impact que la course.';x.steps=[['SÉANCE',s],['INTENSITÉ','Facile signifie que tu dois pouvoir tenir une conversation et terminer sans fatigue musculaire importante.']];x.focus='Cette séance ne doit pas devenir une sortie vélo intense.';x.terms=['RPE'];return x}
 if(walk){x.type=recovery?'Récupération':'Endurance';x.activity='Marche';x.objective=recovery?'Favoriser la récupération en restant actif.':'Construire de l’endurance à faible impact.';x.steps=[['SÉANCE',s],['INTENSITÉ','Marche facile = allure confortable. Marche active = pas plus dynamique, mais toujours sans essoufflement marqué.']];x.focus='La marche est ici la séance prévue, pas un substitut à une course manquée.';x.terms=['RPE'];return x}
 if(low.includes('run/walk')||low.includes('course/marche')){x.type='Endurance';x.activity='Course / marche';x.objective='Construire l’endurance avec une alternance course/marche planifiée.';x.steps=[['SÉANCE',s],['COMMENT LE FAIRE','Respecte l’alternance indiquée dès le début : la phase de marche fait partie de la séance et ne signifie pas que tu as échoué.'],['INTENSITÉ','Les portions courues restent faciles sauf indication contraire. Tu dois pouvoir reprendre chaque bloc sans essoufflement excessif.']];x.focus='N’attends pas d’être épuisé pour marcher : le ratio est une stratégie, pas une solution de secours.';x.terms=['RUN/WALK','RPE'];return x}
 x.type='Endurance';x.activity='Course à pied';x.objective='Développer l’endurance à une allure volontairement confortable.';x.steps=[['SÉANCE',s],['QUE VEUT DIRE « FACILE » ?','Il s’agit d’un footing : tu cours, mais lentement. L’effort reste autour de RPE 3–4, avec une respiration confortable et la possibilité de parler en phrases complètes.'],['FIN DE SÉANCE','Ne transforme pas les dernières minutes en accélération sauf si le plan le demande explicitement.']];x.focus='Sur les journées faciles, courir plus vite n’apporte pas de bonus : respecte l’intention de la séance.';x.terms=['RPE','EF'];return x
}
function glossaryHtml(x){const keys=[...new Set(x.terms||[])].filter(k=>glossary[k]);if(!keys.length)return'';return `<div class="ux-glossary"><h3>Comprendre les termes</h3>${keys.map(k=>`<details><summary>${esc(k)}</summary><p>${esc(glossary[k])}</p></details>`).join('')}</div>`}
function encouragementFor(d){const week=Number(d?.week)||0;const date=d?.date?new Date(d.date+'T12:00:00'):null;const day=date&&!Number.isNaN(date.getTime())?date.getDay():0;return encouragements[(week+day)%encouragements.length]||encouragements[0]}
function openTraining(d){let x=details(d.training),done=window.S?.days?.[d.date]?.done;let modal=document.querySelector('#trainingDetail');if(!modal){modal=document.createElement('div');modal.id='trainingDetail';modal.className='training-modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="training-sheet"><button class="training-close" aria-label="Fermer">×</button><span class="tag">${esc(x.type)} · Semaine ${esc(d.week??'')}</span><h2>${esc(d.training)}</h2><div class="training-meta"><div><small>ACTIVITÉ</small><b>${esc(x.activity)}</b></div><div><small>OBJECTIF</small><b>${esc(x.objective)}</b></div></div><p class="ux-coach">${esc(encouragementFor(d))}</p><div class="training-steps">${x.steps.map(([label,text],i)=>`<div class="training-step${i===1?' main':''}"><small>${esc(label)}</small><b>${esc(text)}</b></div>`).join('')}</div><div class="ux-tip"><b>Le point du coach</b><p>${esc(x.focus)}</p></div>${glossaryHtml(x)}<button class="btn training-to-today">${done?'Voir mon compte-rendu ✓':'Faire cette séance'}</button></div>`;modal.classList.add('open');modal.querySelector('.training-close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};modal.querySelector('.training-to-today').onclick=()=>{modal.classList.remove('open');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector('#today')?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}}
function visibleWeek(){if(typeof window.plan!=='function')return null;const box=document.querySelector('#week');const h=box?.querySelector('h2')?.textContent||'';const m=h.match(/Semaine\s+(\d+)/i);const n=m?+m[1]:null;const weeks=window.plan();return weeks.find(w=>w.week===n)||weeks[0]||null}
function decorate(){if(typeof window.cur!=='function')return;let d=window.cur();if(!d)return;let today=document.querySelector('#today');if(today&&!today.querySelector('.ux-daily')){let first=today.querySelector('.card');if(first){first.classList.add('ux-today-card');let n=document.createElement('div');n.className='ux-daily';n.innerHTML=`<div class="ux-eyebrow">TON CAP DU JOUR</div><p>${esc(encouragementFor(d))}</p><button class="ux-session-btn">Voir le programme de la séance <span>→</span></button>`;first.appendChild(n);n.querySelector('button').onclick=()=>openTraining(d)}}let week=document.querySelector('#week');if(week){const w=visibleWeek();week.querySelectorAll('.row').forEach((r,i)=>{const dd=w?.days?.[i];if(dd&&!r.classList.contains('ux-clickable')){r.classList.add('ux-clickable');r.setAttribute('role','button');r.setAttribute('tabindex','0');r.insertAdjacentHTML('beforeend','<span class="ux-row-arrow">Détails →</span>');r.onclick=()=>openTraining(dd);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openTraining(dd)}}}})}}
let obs=new MutationObserver(()=>requestAnimationFrame(decorate));obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('load',decorate);setTimeout(decorate,300);window.R42_UX={openTraining,glossary,details};
})();